version: '3'
services:
  nextjs:
    build: ./
  nginx:
    build: ./docker/nginx
    networks:
      - default
      - api-net
    ports:
      - 80:80

networks:
  default:
    driver: bridge
  api-net:
    external:
       name: template-adonis_default
